version: "3.9"

services:
  app:
    build: .
    env_file: .env
    ports:
      - "${FASTAPI_PORT:-8000}:${FASTAPI_PORT:-8000}"
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port ${FASTAPI_PORT:-8000}"

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: unless-stopped

volumes:
  pgdata:
